version: '3'
services:
  php:
    image: php:7.4-apache
    container_name: php_container
    ports:
      - "8001:80"
    volumes:
      - ./php:/var/www/html
    networks:
      - backend-labs-network

  node:
    image: node:14
    container_name: node_container
    ports:
      - "8002:3000"
    volumes:
      - ./node:/usr/src/app
    working_dir: /usr/src/app
    command: node index.js
    networks:
      - backend-labs-network

  python:
    image: python:3.9
    container_name: python_container
    ports:
      - "8003:5000"
    volumes:
      - ./python:/app
    working_dir: /app
    command: python app.py
    networks:
      - backend-labs-network

networks:
  backend-labs-network:
    driver: bridge
